export const config = {
  profile: {
    name: "Rohit Shetake",
    title: "Full Stack Developer",
    description: "I build high-performance, visually stunning digital experiences. Specialized in React, Node.js, and pushing the boundaries of web UI.",
    avatar: "/assets/profile-removebg-preview.png",
  },
  navigation: [
    { name: "Home", href: "#home" },
    { name: "About", href: "#about" },
    { name: "Projects", href: "#projects" },
    // { name: "Gallery", href: "#gallery" },
    { name: "Resume", href: "#resume" },
    { name: "Contact", href: "#contact" },
  ],
  about: {
    title: "About Me",
    summary: [
      "I'm a passionate full-stack developer with expertise in building modern web applications. With a keen eye for design and a love for clean code, I create digital experiences that are both beautiful and functional.",
    ],
    experience: [
      {
        role: "Full Stack Developer",
        company: "Accucia Softwares pvt. ltd.",
        period: "mar-2025 - November-2025",
        description: "Leading development of scalable web applications using React, Node.js, and cloud technologies.",
        color: "blue-500",
      },
    ],
  },
  projects: [
    {
      title: "E-Commerce",
      subtitle: "Modern E-Commerce Store",
      value: "ecommerce",
      description: "A fully immersive shopping experience with real-time inventory, secure payments via Stripe, and a lightning-fast dashboard for sellers.",
      image: "https://images.unsplash.com/photo-1557821552-17105176677c?q=60&w=800",
      tech: ["React", "Node.js", "MongoDB", "Stripe", "Tailwind"],
      color: "from-indigo-500 to-purple-500",
      bgGradient: "from-indigo-900 to-black",
    },
    {
      title: "AI Chatbot",
      subtitle: "Intelligent AI Chat",
      value: "aichat",
      description: "A next-generation chatbot interface using GPT-4, featuring markdown support, code highlighting, and persistent conversation history.",
      image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?q=60&w=800",
      tech: ["Next.js", "OpenAI", "WebSocket", "Redis"],
      color: "from-blue-500 to-cyan-500",
      bgGradient: "from-blue-900 to-black",
    },
    {
      title: "SaaS Dashboard",
      subtitle: "Enterprise Dashboard",
      value: "dashboard",
      description: "A comprehensive data visualization platform with interactive charts, user management, and automated reporting systems.",
      image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=60&w=800",
      tech: ["TypeScript", "D3.js", "PostgreSQL", "Prisma"],
      color: "from-emerald-500 to-teal-500",
      bgGradient: "from-emerald-900 to-black",
    },
    {
      title: "Video Editor",
      subtitle: "Cloud Video Editor",
      value: "video",
      description: "Edit videos directly in your browser with real-time preview, timeline management, and seamless cloud rendering.",
      image: "https://images.unsplash.com/photo-1492724441997-5dc865305da7?q=60&w=800",
      tech: ["WebAssembly", "React", "Canvas API", "FFmpeg"],
      color: "from-rose-500 to-orange-500",
      bgGradient: "from-rose-900 to-black",
    },
  ],
  skills: [
    { name: "React", level: 95 },
    { name: "JavaScript", level: 90 },
    { name: "TypeScript", level: 85 },
    { name: "Node.js", level: 88 },
    { name: "Python", level: 80 },
    { name: "Tailwind CSS", level: 92 },
    { name: "MongoDB", level: 85 },
    { name: "AWS", level: 75 },
  ],
  certifications: [
    {
      name: "AWS Certified Developer",
      organization: "Amazon Web Services",
      year: "2023",
    },
    {
      name: "React Advanced Certification",
      organization: "Meta",
      year: "2022",
    },
  ],
  gallery: [
    { id: 1, src: "https://images.unsplash.com/photo-1542038784456-1ea8e935640e?q=80&w=400", x: 100, y: 100 },
    { id: 2, src: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=400", x: 400, y: 150 },
    { id: 3, src: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=400", x: 700, y: 100 },
    { id: 4, src: "https://images.unsplash.com/photo-1510915228340-29c85a43dcfe?q=80&w=400", x: 250, y: 350 },
    { id: 5, src: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400", x: 550, y: 300 },
  ],
  contact: {
    message: "I'm always open to discussing new projects, creative ideas or opportunities to be part of your visions.",
    socials: [
      { name: "GitHub", href: "#", icon: "IconBrandGithub" },
      { name: "Twitter", href: "#", icon: "IconBrandTwitter" },
      { name: "Email", href: "mailto:hello@example.com", icon: "IconMail" },
    ],
  },
};
